package se.mindphaser.skytte.auth

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.tasks.await
import se.mindphaser.skytte.R

/**
 * Wraps Firebase Auth. Exposes the signed-in user's [uid] as a StateFlow (null = signed out) and
 * a one-tap Google sign-in via Credential Manager. The web client id used for sign-in
 * (`default_web_client_id`) is generated by the google-services plugin from `google-services.json`
 * once Google is enabled as an Auth provider in the Firebase console.
 */
class AuthManager(private val appContext: Context) {
    private val auth = FirebaseAuth.getInstance()

    private val _uid = MutableStateFlow(auth.currentUser?.uid)
    val uid: StateFlow<String?> = _uid

    init {
        auth.addAuthStateListener { firebaseAuth -> _uid.value = firebaseAuth.currentUser?.uid }
    }

    /** Launches the Google sign-in sheet and signs the user into Firebase. Must be called with an Activity context. */
    suspend fun signInWithGoogle(activityContext: Context): Result<Unit> = runCatching {
        val credentialManager = CredentialManager.create(activityContext)
        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(appContext.getString(R.string.default_web_client_id))
            .build()
        val request = GetCredentialRequest.Builder().addCredentialOption(googleIdOption).build()

        val response = credentialManager.getCredential(activityContext, request)
        val googleCredential = GoogleIdTokenCredential.createFrom(response.credential.data)
        val firebaseCredential = GoogleAuthProvider.getCredential(googleCredential.idToken, null)
        auth.signInWithCredential(firebaseCredential).await()
        Unit
    }.onFailure { Log.e("AuthManager", "Google sign-in failed", it) }

    fun signOut() = auth.signOut()
}
